[package]
name = "firework_v3"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.2"
noise = "0.9.0"
pollster = "0.4.0"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
wgpu = "26.0.1"
